#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER tt PASSWORD 'tt';
	CREATE DATABASE tt;
	GRANT ALL PRIVILEGES ON DATABASE tt TO tt;
  \connect tt
  CREATE SCHEMA tt;
  GRANT ALL PRIVILEGES ON SCHEMA tt TO tt;
EOSQL
