name: Build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
        os: ['macos-latest', 'ubuntu-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    name: Build with Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn --batch-mode install