/*
 * Copyright (C) 2005-2010 ManyDesigns srl.  All rights reserved.
 * http://www.manydesigns.com/
 *
 * Unless you have purchased a commercial license agreement from ManyDesigns srl,
 * the following license terms apply:
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as published by
 * the Free Software Foundation.
 *
 * There are special exceptions to the terms and conditions of the GPL
 * as it is applied to this software. View the full text of the
 * exception in file OPEN-SOURCE-LICENSE.txt in the directory of this
 * software distribution.
 *
 * This program is distributed WITHOUT ANY WARRANTY; and without the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see http://www.gnu.org/licenses/gpl.txt
 * or write to:
 * Free Software Foundation, Inc.,
 * 59 Temple Place - Suite 330,
 * Boston, MA  02111-1307  USA
 *
 */

package com.manydesigns.elements.fields;

import com.manydesigns.elements.reflection.PropertyAccessor;
import com.manydesigns.elements.xml.XhtmlBuffer;
import com.manydesigns.elements.Mode;
import org.apache.commons.lang.StringUtils;

import javax.servlet.http.HttpServletRequest;
import java.lang.reflect.InvocationTargetException;

/*
* @author Paolo Predonzani     - paolo.predonzani@manydesigns.com
* @author Angelo Lupo          - angelo.lupo@manydesigns.com
* @author Giampiero Granatella - giampiero.granatella@manydesigns.com
*/
public class BooleanField extends AbstractField {
    public static final String copyright =
            "Copyright (c) 2005-2010, ManyDesigns srl";

    public static final String CHECK_PREFIX = "__checkbox_";

    protected boolean booleanValue;
    public static final String TRUE_VALUE = "true";
    public static final String FALSE_VALUE = "false";

    //**************************************************************************
    // Costruttori
    //**************************************************************************
    public BooleanField(PropertyAccessor accessor, Mode mode) {
        this(accessor, mode, null);
    }

    public BooleanField(PropertyAccessor accessor, Mode mode, String prefix) {
        super(accessor, mode, prefix);
        Class type = accessor.getType();
        if (type.isPrimitive()) {
            setRequired(true);
        }
    }

    //**************************************************************************
    // Implementazione di Component
    //**************************************************************************
    public void readFromRequest(HttpServletRequest req) {
        super.readFromRequest(req);

        if (mode.isView(immutable, autogenerated)) {
            return;
        }

        String checkInputName = CHECK_PREFIX + inputName;
        if (req.getParameter(checkInputName) == null) {
            return;
        }
        
        String stringValue = req.getParameter(inputName);
        booleanValue = TRUE_VALUE.equals(stringValue);
    }

    public boolean validate() {
        return true;
    }


    public void readFromObject(Object obj) {
        super.readFromObject(obj);
        try {
            Boolean tmpValue;
            if (obj == null) {
                tmpValue = null;
            } else {
                tmpValue = (Boolean)accessor.get(obj);
            }
            booleanValue = tmpValue != null && tmpValue;
        } catch (IllegalAccessException e) {
            throw new Error(e);
        } catch (InvocationTargetException e) {
            throw new Error(e);
        }
    }

    public void writeToObject(Object obj) {
        writeToObject(obj, booleanValue);
    }

    public void valueToXhtml(XhtmlBuffer xb) {
        String checkInputName = CHECK_PREFIX + inputName;

        if (mode.isView(immutable, autogenerated)) {
            valueToXhtmlView(xb);
        } else if (mode.isEdit()) {
            xb.writeInputCheckbox(id, inputName,
                    TRUE_VALUE, booleanValue, false, "checkbox");
            xb.writeInputHidden(checkInputName, TRUE_VALUE);
        } else if (mode.isPreview()) {
            valueToXhtmlPreview(xb);
        } else if (mode.isHidden()) {
            xb.writeInputHidden(inputName, booleanValue ? TRUE_VALUE : FALSE_VALUE);
            xb.writeInputHidden(checkInputName, TRUE_VALUE);
        } else {
            throw new IllegalStateException("Unknown mode: " + mode);
        }
    }

    private void valueToXhtmlPreview(XhtmlBuffer xb) {
        String checkInputName = CHECK_PREFIX + inputName;

        valueToXhtmlView(xb);
        xb.writeInputHidden(inputName, booleanValue ? TRUE_VALUE : FALSE_VALUE);
        xb.writeInputHidden(checkInputName, TRUE_VALUE);
    }

    private void valueToXhtmlView(XhtmlBuffer xb) {
        xb.openElement("div");
        xb.addAttribute("class", "value");
        xb.addAttribute("id", id);
        if (href != null) {
            xb.openElement("a");
            xb.addAttribute("href", href);
        }
        xb.write(getStringValue());
        if (href != null) {
            xb.closeElement("a");
        }
        xb.closeElement("div");
    }

    public String getStringValue() {
        return booleanValue ? getText("elements.Yes") : getText("elements.No");
    }

    //**************************************************************************
    // Other methods
    //**************************************************************************
    public void labelToXhtml(XhtmlBuffer xb) {
        xb.openElement("label");
        xb.addAttribute("for", id);
        xb.addAttribute("class", "field");
        xb.write(StringUtils.capitalize(label + ":"));
        xb.closeElement("label");
    }

    //**************************************************************************
    // Getter/setter
    //**************************************************************************
    public boolean getBooleanValue() {
        return booleanValue;
    }
}
