/*
 * Copyright (C) 2005-2010 ManyDesigns srl.  All rights reserved.
 * http://www.manydesigns.com/
 *
 * Unless you have purchased a commercial license agreement from ManyDesigns srl,
 * the following license terms apply:
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as published by
 * the Free Software Foundation.
 *
 * There are special exceptions to the terms and conditions of the GPL
 * as it is applied to this software. View the full text of the
 * exception in file OPEN-SOURCE-LICENSE.txt in the directory of this
 * software distribution.
 *
 * This program is distributed WITHOUT ANY WARRANTY; and without the
 * implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see http://www.gnu.org/licenses/gpl.txt
 * or write to:
 * Free Software Foundation, Inc.,
 * 59 Temple Place - Suite 330,
 * Boston, MA  02111-1307  USA
 *
 */

package com.manydesigns.elements.fields;

import com.manydesigns.elements.Mode;
import com.manydesigns.elements.annotations.Select;
import com.manydesigns.elements.json.JsonBuffer;
import com.manydesigns.elements.options.DefaultSelectionProvider;
import com.manydesigns.elements.options.SelectionModel;
import com.manydesigns.elements.options.SelectionProvider;
import com.manydesigns.elements.reflection.PropertyAccessor;
import com.manydesigns.elements.util.Util;
import com.manydesigns.elements.xml.XhtmlBuffer;
import org.apache.commons.lang.StringEscapeUtils;

import javax.servlet.http.HttpServletRequest;
import java.lang.reflect.InvocationTargetException;
import java.text.MessageFormat;
import java.util.Map;

/*
 * @author Paolo Predonzani     - paolo.predonzani@manydesigns.com
 * @author Angelo Lupo          - angelo.lupo@manydesigns.com
 * @author Giampiero Granatella - giampiero.granatella@manydesigns.com
 */
public class SelectField extends AbstractField {
    public static final String copyright =
            "Copyright (c) 2005-2010, ManyDesigns srl";

    public final static String AUTOCOMPLETE_SUFFIX = "_autocomplete";

    protected SelectionModel selectionModel;
    protected int selectionModelIndex;
    protected SelectField previousSelectField;
    protected SelectField nextSelectField;

    protected String comboLabel;

    protected String autocompleteId;
    protected String autocompleteInputName;

    //**************************************************************************
    // Costruttori
    //**************************************************************************
    public SelectField(PropertyAccessor accessor, Mode mode, String prefix) {
        super(accessor, mode, prefix);

        Select annotation = accessor.getAnnotation(Select.class);
        if (annotation != null) {
            Object[] values = annotation.values();
            String[] labels = annotation.labels();
            assert(values.length == labels.length);
            SelectionProvider selectionProvider =
                    DefaultSelectionProvider.create(
                            accessor.getName(), 1, values, labels);
            selectionModel = selectionProvider.createSelectionModel();
            selectionModelIndex = 0;
        }

        comboLabel = MessageFormat.format("-- Select {0} --", label);
        autocompleteId = id + AUTOCOMPLETE_SUFFIX;
        autocompleteInputName = inputName + AUTOCOMPLETE_SUFFIX;
    }

    //**************************************************************************
    // Element implementation
    //**************************************************************************

    public void readFromRequest(HttpServletRequest req) {
        super.readFromRequest(req);

        if (mode.isView(immutable, autogenerated)) {
            return;
        }

        String stringValue = req.getParameter(inputName);
        Object value = Util.convertValue(stringValue, accessor.getType());
        selectionModel.setValue(selectionModelIndex, value);
    }

    public boolean validate() {
        if (mode.isView(immutable, autogenerated)
                || (mode.isBulk() && !bulkChecked)) {
            return true;
        }

        Object value = selectionModel.getValue(selectionModelIndex);
        if (required && value == null) {
            errors.add(getText("elements.error.field.required"));
            return false;
        }
        return true;
    }

    public void readFromObject(Object obj) {
        super.readFromObject(obj);
        try {
            if (obj == null) {
                setValue(null);
            } else {
                setValue(accessor.get(obj));
            }
        } catch (IllegalAccessException e) {
            throw new Error(e);
        } catch (InvocationTargetException e) {
            throw new Error(e);
        }
    }

    public void writeToObject(Object obj) {
        Object value = selectionModel.getValue(selectionModelIndex);
        writeToObject(obj, value);
    }

    public void valueToXhtml(XhtmlBuffer xb) {
        if (mode.isView(immutable, autogenerated)) {
            valueToXhtmlView(xb);
        } else if (mode.isEdit()) {
            valueToXhtmlEdit(xb);
        } else if (mode.isPreview()) {
            valueToXhtmlPreview(xb);
        } else if (mode.isHidden()) {
            valueToXhtmlHidden(xb);
        } else {
            throw new IllegalStateException("Unknown mode: " + mode);
        }
    }

    private void valueToXhtmlEdit(XhtmlBuffer xb) {
        if (selectionModel.getSelectionProvider().isAutocomplete()) {
            valueToXhtmlEditAutocomplete(xb);
        } else {
            valueToXhtmlEditDropDown(xb);
        }
    }

    protected void valueToXhtmlEditDropDown(XhtmlBuffer xb) {
        Object value = selectionModel.getValue(selectionModelIndex);
        Map<Object, String> options =
                selectionModel.getOptions(selectionModelIndex);

        xb.openElement("select");
        xb.addAttribute("id", id);
        xb.addAttribute("name", inputName);

        boolean checked = (value == null);
        if (!options.isEmpty()) {
            xb.writeOption("", checked, comboLabel);
        }

        for (Map.Entry<Object,String> option :
                options.entrySet()) {
            Object optionValue = option.getKey();
            String optionStringValue =
                    (String) Util.convertValue(optionValue, String.class);
            String optionLabel = option.getValue();
            checked =  optionValue.equals(value);
            xb.writeOption(optionStringValue, checked, optionLabel);
        }
        xb.closeElement("select");

        String js = composeDropDownJs();

        xb.openElement("script");
        xb.write(js);
        xb.closeElement("script");

    }

    protected String composeDropDownJs() {
        StringBuilder sb = new StringBuilder();
        sb.append(MessageFormat.format(
                "$(''#{0}'').change(" +
                        "function() '{'" +
                        "updateSelectOptions(''{1}'', {2}",
                StringEscapeUtils.escapeJavaScript(id),
                StringEscapeUtils.escapeJavaScript(selectionModel.getName()),
                selectionModelIndex + 1));
        appendIds(sb);
        sb.append(");});");
        return sb.toString();
    }

    protected String composeAutocompleteJs() {
        StringBuilder sb = new StringBuilder();
        sb.append(MessageFormat.format(
                "setupAutocomplete(''#{0}'', ''{1}'', {2}",
                StringEscapeUtils.escapeJavaScript(autocompleteId),
                StringEscapeUtils.escapeJavaScript(selectionModel.getName()),
                selectionModelIndex));
        appendIds(sb);
        sb.append(");");
        return sb.toString();
    }



    private void appendIds(StringBuilder sb) {
        SelectField rootField = this;
        while (rootField.previousSelectField != null) {
            rootField = rootField.previousSelectField;
        }
        SelectField currentField = rootField;
        while (currentField != null) {
            sb.append(MessageFormat.format(", ''#{0}''",
                    StringEscapeUtils.escapeJavaScript(currentField.getId())));
            currentField = currentField.nextSelectField;
        }
    }

    protected void valueToXhtmlEditAutocomplete(XhtmlBuffer xb) {
        Object value = selectionModel.getValue(selectionModelIndex);
        Map<Object, String> options =
                selectionModel.getOptions(selectionModelIndex);
        String stringValue = Util.convertValueToString(value);
        xb.writeInputHidden(id, inputName, stringValue);

        xb.openElement("input");
        xb.addAttribute("id", autocompleteId);
        xb.addAttribute("type", "text");
        xb.addAttribute("name", autocompleteInputName);
        xb.addAttribute("value", options.get(value));
        xb.addAttribute("class", null);
        xb.addAttribute("size", null);
        xb.closeElement("input");

        String js = composeAutocompleteJs();

        xb.openElement("script");
        xb.write(js);
        xb.closeElement("script");
    }

    public void valueToXhtmlPreview(XhtmlBuffer xb) {
        valueToXhtmlView(xb);
        valueToXhtmlHidden(xb);
    }

    private void valueToXhtmlHidden(XhtmlBuffer xb) {
        Object value = selectionModel.getValue(selectionModelIndex);
        String stringValue = Util.convertValueToString(value);
        xb.writeInputHidden(id, inputName, stringValue);
    }

    public void valueToXhtmlView(XhtmlBuffer xb) {
        Object value = selectionModel.getValue(selectionModelIndex);
        Map<Object, String> options =
                selectionModel.getOptions(selectionModelIndex);
        xb.openElement("div");
        xb.addAttribute("class", "value");
        xb.addAttribute("id", id);
        if (href != null) {
            xb.openElement("a");
            xb.addAttribute("href", href);
        }
        xb.write(options.get(value));
        if (href != null) {
            xb.closeElement("a");
        }
        xb.closeElement("div");
    }

    public String jsonSelectFieldOptions(boolean includeSelectPrompt) {
        Map<Object, String> options =
                selectionModel.getOptions(selectionModelIndex);
        // prepariamo Json
        JsonBuffer jb = new JsonBuffer();

        // apertura array Json
        jb.openArray();

        if (includeSelectPrompt && !options.isEmpty()) {
            jb.openObject();
            jb.writeKeyValue("v", ""); // value
            jb.writeKeyValue("l", comboLabel); // label
            jb.writeKeyValue("s", true); // selected
            jb.closeObject();
        }

        for (Map.Entry<Object,String> option : options.entrySet()) {
            jb.openObject();
            Object optionValue = option.getKey();
            String optionStringValue = Util.convertValueToString(optionValue);
            String optionLabel = option.getValue();

            jb.writeKeyValue("v", optionStringValue);
            jb.writeKeyValue("l", optionLabel);
            jb.writeKeyValue("s", false);
            jb.closeObject();
        }

        // chiusura array Json
        jb.closeArray();

        return jb.toString();
    }

    //**************************************************************************
    // Getters/setters
    //**************************************************************************

    public Object getValue() {
        return selectionModel.getValue(selectionModelIndex);
    }

    public void setValue(Object value) {
        selectionModel.setValue(selectionModelIndex, value);
    }

    public Map<Object, String> getOptions() {
        return selectionModel.getOptions(selectionModelIndex);
    }

    public String getLabelSearch() {
        return selectionModel.getLabelSearch(selectionModelIndex);
    }

    public String getComboLabel() {
        return comboLabel;
    }

    public void setComboLabel(String comboLabel) {
        this.comboLabel = comboLabel;
    }

    public String getAutocompleteId() {
        return autocompleteId;
    }

    public SelectField getNextSelectField() {
        return nextSelectField;
    }

    public void setNextSelectField(SelectField nextSelectField) {
        this.nextSelectField = nextSelectField;
    }

    public SelectField getPreviousSelectField() {
        return previousSelectField;
    }

    public void setPreviousSelectField(SelectField previousSelectField) {
        this.previousSelectField = previousSelectField;
    }

    public void setAutocompleteId(String autocompleteId) {
        this.autocompleteId = autocompleteId;
    }

    public String getAutocompleteInputName() {
        return autocompleteInputName;
    }

    public void setAutocompleteInputName(String autocompleteInputName) {
        this.autocompleteInputName = autocompleteInputName;
    }

    public void setLabelSearch(String labelSearch) {
        selectionModel.setLabelSearch(selectionModelIndex, labelSearch);
    }

    public SelectionModel getSelectionModel() {
        return selectionModel;
    }

    public void setSelectionModel(SelectionModel selectionModel) {
        this.selectionModel = selectionModel;
    }

    public int getSelectionModelIndex() {
        return selectionModelIndex;
    }

    public void setSelectionModelIndex(int selectionModelIndex) {
        this.selectionModelIndex = selectionModelIndex;
    }
}
